#ifndef ZEBRAFX7500_GLOBAL_H
#define ZEBRAFX7500_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZEBRAFX7500_LIBRARY)
#  define ZEBRAFX7500_EXPORT Q_DECL_EXPORT
#else
#  define ZEBRAFX7500_EXPORT Q_DECL_IMPORT
#endif

#endif // ZEBRAFX7500_GLOBAL_H
